import 'package:atlas_icons/atlas_icons.dart';
import 'package:flutter/material.dart';

/// custom icons are prefixed with [ki]
const IconData kiArrowBack = Icons.arrow_back_outlined;
const IconData kiArrowNext = Icons.arrow_forward_outlined;
const IconData kiArrowForward = Icons.arrow_right_alt;
const IconData kiClose = Atlas.xmark_circle_thin;
const IconData kiCircle = Icons.circle;
const IconData kiMouseScroll = Atlas.mouse_pointer_up;
const IconData kiLink = Atlas.chain;
const IconData kiCode = Atlas.programming;
const IconData kiFolder = Atlas.folder_archive;
const IconData kiChip = Atlas.computer_chip;
const IconData kiPhone = Atlas.mobile_pen;
const IconData kiLaptop = Atlas.laptop;
const IconData kiTag = Atlas.leaf_tag;
const IconData kiMorning = Atlas.sunrise;
const IconData kiPerson = Atlas.person_vr_glasses;
const IconData kiCoding = Atlas.remote_working;
const IconData kiReading = Atlas.heart_book;
const IconData kiCoffee = Atlas.tea_coffee;
const IconData kiMusic = Atlas.heart_music;
const IconData kiExplore = Atlas.compass_pointers;
const IconData kiMovie = Atlas.movie_film;
const IconData kiTrophy = Atlas.trophy_star_reward;
const IconData kiActivity = Atlas.diploma_certificate;
const IconData kiMemo = Atlas.memo_thin;
const IconData kiError = Atlas.exclamation_chat;
const IconData kiSuccess = Atlas.check_message;
const IconData kiMail = Atlas.mailbox;
const IconData kiCredit = Atlas.star_trophy_achievement;
const IconData kiHeart = Atlas.heart_arrow_bold;
